# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: article.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='article.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\rarticle.proto\"\xac\x02\n\x07\x41rticle\x12\x12\n\narticle_id\x18\x01 \x01(\x05\x12\x17\n\x0f\x61rticle_excerpt\x18\x02 \x01(\t\x12\x17\n\x0f\x61rticle_picture\x18\x03 \x03(\t\x12\x19\n\x11\x61rticle_pagecount\x18\x04 \x01(\x05\x12*\n\x0c\x61rticle_type\x18\x05 \x01(\x0e\x32\x14.Article.ArticleType\x12\x1f\n\x06\x61uthor\x18\x06 \x01(\x0b\x32\x0f.Article.Author\x1a%\n\x06\x41uthor\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05phone\x18\x02 \x01(\t\":\n\x0b\x41rticleType\x12\t\n\x05NOVEL\x10\x00\x12\t\n\x05PROSE\x10\x01\x12\t\n\x05PAPER\x10\x02\x12\n\n\x06POETRY\x10\x03J\x04\x08\t\x10\nJ\x04\x08\n\x10\x0bJ\x04\x08\x0c\x10\x10\"K\n\x05Other\x12\x12\n\nother_info\x18\x01 \x01(\t\x12\x0f\n\x05\x63ode1\x18\x02 \x01(\tH\x00\x12\x0f\n\x05\x63ode2\x18\x03 \x01(\tH\x00\x42\x0c\n\ntest_oneofb\x06proto3')
)



_ARTICLE_ARTICLETYPE = _descriptor.EnumDescriptor(
  name='ArticleType',
  full_name='Article.ArticleType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NOVEL', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PROSE', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PAPER', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='POETRY', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=242,
  serialized_end=300,
)
_sym_db.RegisterEnumDescriptor(_ARTICLE_ARTICLETYPE)


_ARTICLE_AUTHOR = _descriptor.Descriptor(
  name='Author',
  full_name='Article.Author',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='Article.Author.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='phone', full_name='Article.Author.phone', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=203,
  serialized_end=240,
)

_ARTICLE = _descriptor.Descriptor(
  name='Article',
  full_name='Article',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='article_id', full_name='Article.article_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='article_excerpt', full_name='Article.article_excerpt', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='article_picture', full_name='Article.article_picture', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='article_pagecount', full_name='Article.article_pagecount', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='article_type', full_name='Article.article_type', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='author', full_name='Article.author', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_ARTICLE_AUTHOR, ],
  enum_types=[
    _ARTICLE_ARTICLETYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=318,
)


_OTHER = _descriptor.Descriptor(
  name='Other',
  full_name='Other',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='other_info', full_name='Other.other_info', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='code1', full_name='Other.code1', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='code2', full_name='Other.code2', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='test_oneof', full_name='Other.test_oneof',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=320,
  serialized_end=395,
)

_ARTICLE_AUTHOR.containing_type = _ARTICLE
_ARTICLE.fields_by_name['article_type'].enum_type = _ARTICLE_ARTICLETYPE
_ARTICLE.fields_by_name['author'].message_type = _ARTICLE_AUTHOR
_ARTICLE_ARTICLETYPE.containing_type = _ARTICLE
_OTHER.oneofs_by_name['test_oneof'].fields.append(
  _OTHER.fields_by_name['code1'])
_OTHER.fields_by_name['code1'].containing_oneof = _OTHER.oneofs_by_name['test_oneof']
_OTHER.oneofs_by_name['test_oneof'].fields.append(
  _OTHER.fields_by_name['code2'])
_OTHER.fields_by_name['code2'].containing_oneof = _OTHER.oneofs_by_name['test_oneof']
DESCRIPTOR.message_types_by_name['Article'] = _ARTICLE
DESCRIPTOR.message_types_by_name['Other'] = _OTHER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Article = _reflection.GeneratedProtocolMessageType('Article', (_message.Message,), dict(

  Author = _reflection.GeneratedProtocolMessageType('Author', (_message.Message,), dict(
    DESCRIPTOR = _ARTICLE_AUTHOR,
    __module__ = 'article_pb2'
    # @@protoc_insertion_point(class_scope:Article.Author)
    ))
  ,
  DESCRIPTOR = _ARTICLE,
  __module__ = 'article_pb2'
  # @@protoc_insertion_point(class_scope:Article)
  ))
_sym_db.RegisterMessage(Article)
_sym_db.RegisterMessage(Article.Author)

Other = _reflection.GeneratedProtocolMessageType('Other', (_message.Message,), dict(
  DESCRIPTOR = _OTHER,
  __module__ = 'article_pb2'
  # @@protoc_insertion_point(class_scope:Other)
  ))
_sym_db.RegisterMessage(Other)


# @@protoc_insertion_point(module_scope)
